# Generated by Django 4.0.2 on 2022-02-21 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carsh', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cars',
            old_name='carts_id',
            new_name='cars_id',
        ),
    ]
