# Generated by Django 4.0.2 on 2022-02-22 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('carsh', '0002_rename_carts_id_cars_cars_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cars',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='CarsItem',
            new_name='CartItem',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='cars_id',
            new_name='cart_id',
        ),
        migrations.RenameField(
            model_name='cartitem',
            old_name='cars',
            new_name='cart',
        ),
    ]
